# DigitalOcean App Platform Specification
name: nigeria-security-ews
region: fra

# Services
services:
  # Backend API Service
  - name: backend
    github:
      repo: aydeggy-dot/GEOINT
      branch: main
      deploy_on_push: true
    source_dir: /backend

    # Build configuration
    build_command: pip install --upgrade pip && pip install -r requirements.txt

    # Run configuration
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 2

    # Environment variables (you'll set actual values in DO dashboard)
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "PLACEHOLDER_POSTGRES_URL"

      - key: REDIS_URL
        scope: RUN_TIME
        value: "PLACEHOLDER_VALKEY_URL"

      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "JXOkBs3jk0Sx_uYPWqYOtauI_ng-w6pr7_9T_mzOIyg"

      - key: ENVIRONMENT
        scope: RUN_TIME
        value: "production"

      - key: FRONTEND_URL
        scope: RUN_TIME
        value: "https://nigeria-security-ews.ondigitalocean.app"

      - key: ALLOWED_ORIGINS
        scope: RUN_TIME
        value: '["https://nigeria-security-ews.ondigitalocean.app"]'

      - key: JWT_ALGORITHM
        scope: RUN_TIME
        value: "HS256"

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "30"

      - key: REFRESH_TOKEN_EXPIRE_DAYS
        scope: RUN_TIME
        value: "7"

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 15

    # HTTP Routes - backend serves API endpoints
    routes:
      - path: /api

    # Resource configuration
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs

  # Frontend Static Site using Dockerfile
  - name: frontend
    type: static_site
    github:
      repo: aydeggy-dot/GEOINT
      branch: main
      deploy_on_push: true
    source_dir: /frontend

    # Dockerfile build for static site
    dockerfile_path: frontend/Dockerfile

    # Environment variables for build
    envs:
      - key: VITE_API_BASE_URL
        scope: BUILD_TIME
        value: "https://nigeria-security-ews-tiqle.ondigitalocean.app/api/v1"

    # Output directory from Dockerfile
    output_dir: /app/dist

    # Static site routing
    catchall_document: index.html
    routes:
      - path: /
